### ISSUE TITLE
Image not loading correctly on FF 35 and Safari

### ISSUE THREAD

**Issue by morenoh149** [chenglou/react-tween-state#23]
Hello. Great plugin here.
I'm using it to build http://r3dmqa.herokuapp.com/ but we're having issues getting the animation right
on FF 35 and Safari.
Does react-tween-state support Safari?

https://github.com/hzdg/react-imageloader/issues/10

**Comment by chenglou** [comment]
Can you give a repro on jsfiddle or something? That first link errors

**Comment by morenoh149** [comment]
we fixed it since the question was raised. Thanks.
