### ISSUE TITLE
React 0.13 and es6 Classes

### ISSUE THREAD

**Issue by jmfurlott** [chenglou/react-tween-state#26]
Is it possible to use react-tween-state with the new class style? Can't use mixins anymore, so what would it take for this to work?

**Comment by natew** [comment]
I think just moving the need for tweenQueue to be in state and instead put it on the class itself, and then adding this to the prototype somehow.

**Comment by natew** [comment]
I implemented as a mixin that works here, you can even use it as a decorator with babel 5:

https://github.com/reapp/reapp-ui/blob/master/src/decorators/Tweenable.js

```js
@Tweenable
class MyClass extends React.Component {}
```

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by frederickfogerty** [comment]
@natew this errors, as trying to assign `getInitialState` on a plain class is not supported at the moment.

**Comment by natew** [comment]
@frederickfogerty If you use it with my pull request on this repo it should work, may be some bugs but it works for me.

**Comment by frederickfogerty** [comment]
Will have a look now :+1:

**Comment by chrisvfritz** [comment]
:+1: Would also love to see this work without mixins. Component wrappers are a popular alternative that will not only work with ES6 classes, but also CoffeeScript, TypeScript, LiveScript, etc.

**Comment by rob-balfre** [comment]
:+1:

**Comment by frederickfogerty** [comment]
To be honest, we should all just use https://github.com/chenglou/react-motion. I'm moving all my tween-state code to it at the moment

**Comment by rob-balfre** [comment]
@frederickfogerty nice, will take a look. Thanks!

**Comment by chenglou** [comment]
I think I'll keep this library as a mixin. React-motion already fills most of the transition needs and if the demand is high for normal easing, I'll implement it over there. This library's stable, and changing the API to use classes breaks too many existing call sites. Besides, React might move away from classes now.

Closing! Thanks for all the discussion. Go check React-motion! =)

**Comment by chrisvfritz** [comment]
> React might move away from classes now.

This caught my interest as I teach React and want to make sure I'm up to date. I thought ES6 classes were enouraged. Did I miss an announcement somewhere?

**Comment by chenglou** [comment]
Nah it's a might. So no news worth spreading for now. Check https://github.com/reactjs/react-future

Also: https://twitter.com/sebmarkbage/status/646473000749928448

**Comment by chrisvfritz** [comment]
Thanks! I gotta stay on top of these tweets. :smiley:
