### ISSUE TITLE
something happen

### ISSUE THREAD

**Issue by suhaotian** [chenglou/react-tween-state#32]
I run the example,but: Uncaught Error: Invariant Violation: setState(...): takes an object of state variables to update.

**Comment by chenglou** [comment]
Are you running the master version? The official 0.0.5 version is the last one that's compatible with with React < 0.13, because the behavior of setState has changed since.

I think that's it. If that's not the case please reopen the issue! =)

**Comment by suhaotian** [comment]
@chenglou tks :+1:
