### ISSUE TITLE
Looping behaviors (onEnd) and react-native

### ISSUE THREAD

**Issue by morukutsu** [chenglou/react-tween-state#43]
Looping behaviors seems to be broken on react-native. I tested the first example (examples/example1.jsx) which calls **tweenState** again each time **onEnd** is triggered in the browser and it's working fine.

Here a similar example for react-native: https://gist.github.com/morukutsu/c3b01e7946104f4d87af
The behavior is different: 
* tweenState is only called two times ("Called" will be printed only two times)
The counter stops after it reached 1000.

Is there any known issue that could explain this?

I am not really sure it is a react-tween-state, react-native or another unrelated issue.

Thanks a lot !

**Comment by chenglou** [comment]
Hey, what's up! Sorry I don't get notified for new issues so I totally did not see this. Is this fixed?
