### ISSUE TITLE
react-tween-state not work in react native?

### ISSUE THREAD

**Issue by DexterYan** [chenglou/react-tween-state#44]
I am tyring to use react-tween-state  in react native, but when I add var React = require('react-native'); it can't work. You can check this example https://rnplay.org/apps/4FUQ-A .The office example is not work too. Thx

**Comment by chenglou** [comment]
It works for me here?

**Comment by austin1030** [comment]
With react-native v0.7.x it complains that react-tween-state as unknown module.

**Comment by chenglou** [comment]
Really? Can you provide the full error please?

**Comment by chenglou** [comment]
Tried on RN and it works, I'll close this unless there's a clear repro. Thanks!
