### ISSUE TITLE
What is the difference with react-motion?

### ISSUE THREAD

**Issue by bjrmatos** [chenglou/react-tween-state#45]
I'm not an animation expert, could you explain me the difference with [react-motion](https://github.com/chenglou/react-motion)?

**Comment by bjrmatos** [comment]
And [react-state-stream](https://github.com/chenglou/react-state-stream)?

**Comment by jschr** [comment]
+1

**Comment by chenglou** [comment]
Ah, I intended to write this soon. Just been caught up with releasing react-motion. Post coming soon!

As for react-state-stream, it's always been intended as an iteration tool of mine, which is why I've never exposed it on npm. I'll also clarify that in that repo.

**Comment by bjrmatos** [comment]
thnks @chenglou, i'll be waiting to see that Post :)

**Comment by webyak** [comment]
+1 I think too, the differences should definitely be highlighted.

**Comment by chenglou** [comment]
Here's a very relevant post: https://medium.com/@chenglou/react-motion-and-animated-4b3edf671cba

**Comment by webyak** [comment]
Wow, this was fast! Big thanks

**Comment by bjrmatos** [comment]
:clap:
